steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/${PROJECT_ID}/decoles-liatrio-excercise:latest', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/${PROJECT_ID}/decoles-liatrio-excercise:latest']
           
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ 'config', 'set', 'compute/zone', 'us-west1-b']
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'update-container', 'instance-1',
           '--container-image', 'gcr.io/${PROJECT_ID}/decoles-liatrio-excercise:latest']
